name: Update AoC Badges
on:
  schedule:
    - cron: '6 5 1-25 12 *'                      # from the 1. December till 25. December every day at 5:06am (avoid load at full hours)
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1721685                       # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}   # secret containing session code, see setup on how to obtain

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          file_pattern: README.md
          commit_message: Updating Advent of Code stats
